import type { DB, FirmSettings, User, Client, Job, AMC, Attendance, SalaryRecord, TaDa, Transaction, LedgerEntry } from "./types";

const firm: FirmSettings = {
  name: "FixitPoint360",
  tagline: "Complete IT & Home Services",
  contactNo: "9752990613",
  email: "sanjaykumarpatel613@gmail.com",
  address: "Village Mairtola, PO Bhamraha 1st, Tah Beohari, Dist. Shahdol, MP",
  gstin: "",
  currency: "₹",
};

const users: User[] = [
  {
    id: "u-owner",
    name: "Sanjay Patel",
    email: "sanjaykumarpatel613@gmail.com",
    phone: "9752990613",
    password: "owner123",
    role: "owner",
    designation: "Owner",
    status: "active",
    salary: 0,
    commissionRate: 0,
    joinedAt: "2024-01-01",
  },
  {
    id: "u-staff1",
    name: "Ramesh Verma",
    email: "ramesh@fixitpoint360.com",
    phone: "9876543210",
    password: "staff123",
    role: "staff",
    designation: "Technician",
    status: "active",
    salary: 12000,
    commissionRate: 5,
    joinedAt: "2024-03-01",
  },
  {
    id: "u-staff2",
    name: "Amit Singh",
    email: "amit@fixitpoint360.com",
    phone: "9876543211",
    password: "staff123",
    role: "staff",
    designation: "Computer / Printer Technician",
    status: "active",
    salary: 10000,
    commissionRate: 4,
    joinedAt: "2024-05-01",
  },
];

const clients: Client[] = [
  {
    id: "c-1",
    name: "Rahul Sharma",
    phone: "9876541230",
    email: "rahul@gmail.com",
    address: "Ward 12, Beohari",
    city: "Beohari",
    pincode: "484774",
    type: "residential",
    notes: "Prefers WhatsApp messages",
    createdAt: "2024-01-15",
  },
  {
    id: "c-2",
    name: "Shree Ganesh Traders",
    phone: "9425167890",
    email: "ganesh.traders@gmail.com",
    address: "Main Market, Beohari",
    city: "Beohari",
    pincode: "484774",
    type: "business",
    gstin: "23XXXXX0000X1Z5",
    notes: "2 CCTV cameras + billing printer on AMC",
    createdAt: "2024-02-01",
  },
  {
    id: "c-3",
    name: "District Hospital",
    phone: "7694012345",
    email: "hospital.shahdol@mp.gov.in",
    address: "Civil Lines, Shahdol",
    city: "Shahdol",
    pincode: "484001",
    type: "corporate",
    notes: "AMC - computers & printers",
    createdAt: "2024-02-20",
  },
  {
    id: "c-4",
    name: "Priya Gupta",
    phone: "9827754321",
    email: "priya.gupta@gmail.com",
    address: "Gali No 4, Bhamraha",
    city: "Shahdol",
    pincode: "484774",
    type: "residential",
    createdAt: "2024-06-10",
  },
];

const jobs: Job[] = [
  {
    id: "j-1",
    jobNo: 1,
    clientId: "c-2",
    category: "cctv",
    title: "CCTV camera installation (4 cameras)",
    description: "Install 4 HD cameras at shop with DVR and remote viewing",
    status: "completed",
    priority: "normal",
    assignedTo: "u-staff1",
    scheduledDate: "2024-07-05",
    completedDate: "2024-07-06",
    charges: 18500,
    materialCost: 14500,
    advance: 5000,
    paymentStatus: "partial",
    paymentMode: "cash",
    notes: "Customer will pay remaining after GST bill",
    createdAt: "2024-07-04",
    createdBy: "u-owner",
  },
  {
    id: "j-2",
    jobNo: 2,
    clientId: "c-3",
    category: "printer",
    title: "Printer cartridge refilling (HP 138A)",
    description: "Refill 3 cartridges and clean printer head",
    status: "completed",
    priority: "high",
    assignedTo: "u-staff2",
    scheduledDate: "2024-07-12",
    completedDate: "2024-07-12",
    charges: 3600,
    materialCost: 1500,
    advance: 0,
    paymentStatus: "paid",
    paymentMode: "upi",
    createdAt: "2024-07-11",
    createdBy: "u-owner",
  },
  {
    id: "j-3",
    jobNo: 3,
    clientId: "c-1",
    category: "computer",
    title: "Desktop not turning on",
    description: "Power supply unit replacement and RAM cleaning",
    status: "in_progress",
    priority: "urgent",
    assignedTo: "u-staff2",
    scheduledDate: "2024-07-20",
    charges: 2500,
    materialCost: 1200,
    advance: 500,
    paymentStatus: "partial",
    paymentMode: "cash",
    createdAt: "2024-07-19",
    createdBy: "u-owner",
  },
  {
    id: "j-4",
    jobNo: 4,
    clientId: "c-4",
    category: "household",
    title: "Ceiling fan repair + new wiring point",
    description: "Fan not rotating; add new switchboard point",
    status: "pending",
    priority: "normal",
    scheduledDate: "2024-08-05",
    charges: 800,
    materialCost: 350,
    advance: 0,
    paymentStatus: "unpaid",
    paymentMode: "pending",
    createdAt: "2024-07-28",
    createdBy: "u-owner",
  },
];

const amcs: AMC[] = [
  {
    id: "a-1",
    clientId: "c-2",
    category: "cctv",
    planName: "CCTV AMC - Gold",
    amount: 1200,
    billingCycle: "monthly",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    status: "active",
    notes: "4 cameras quarterly servicing",
    createdAt: "2024-01-01",
  },
  {
    id: "a-2",
    clientId: "c-3",
    category: "printer",
    planName: "Printer & Computer AMC - Hospital",
    amount: 2500,
    billingCycle: "monthly",
    startDate: "2024-02-01",
    endDate: "2025-01-31",
    status: "active",
    notes: "5 computers + 3 printers, monthly visit",
    createdAt: "2024-02-01",
  },
];

const attendance: Attendance[] = [
  { id: "at-1", staffId: "u-staff1", date: "2024-07-01", status: "present", checkIn: "09:00", checkOut: "18:30" },
  { id: "at-2", staffId: "u-staff1", date: "2024-07-02", status: "present", checkIn: "09:15", checkOut: "18:00" },
  { id: "at-3", staffId: "u-staff2", date: "2024-07-01", status: "present", checkIn: "09:05", checkOut: "17:45" },
  { id: "at-4", staffId: "u-staff2", date: "2024-07-02", status: "half_day", checkIn: "09:30", checkOut: "13:00" },
];

const salary: SalaryRecord[] = [
  {
    id: "s-1",
    staffId: "u-staff1",
    month: "2024-07",
    presentDays: 26,
    basic: 12000,
    commission: 925,
    taDa: 600,
    bonus: 0,
    deductions: 0,
    net: 13525,
    paid: false,
    notes: "Commission on job #1",
  },
];

const tada: TaDa[] = [
  { id: "t-1", staffId: "u-staff1", date: "2024-07-05", type: "travel", amount: 350, description: "Shahdol site visit", jobId: "j-1" },
  { id: "t-2", staffId: "u-staff1", date: "2024-07-06", type: "daily_allowance", amount: 250, description: "2nd day on job #1", jobId: "j-1" },
];

const transactions: Transaction[] = [
  {
    id: "tx-1",
    type: "income",
    category: "Job / Service",
    amount: 5000,
    date: "2024-07-06",
    mode: "cash",
    clientId: "c-2",
    jobId: "j-1",
    description: "Advance - CCTV installation",
    createdAt: "2024-07-06",
  },
  {
    id: "tx-2",
    type: "income",
    category: "Job / Service",
    amount: 3600,
    date: "2024-07-12",
    mode: "upi",
    clientId: "c-3",
    jobId: "j-2",
    description: "Cartridge refilling",
    createdAt: "2024-07-12",
  },
  {
    id: "tx-3",
    type: "income",
    category: "AMC",
    amount: 1200,
    date: "2024-07-01",
    mode: "cash",
    clientId: "c-2",
    description: "AMC monthly - July",
    createdAt: "2024-07-01",
  },
  {
    id: "tx-4",
    type: "expense",
    category: "Material / Parts",
    amount: 14500,
    date: "2024-07-04",
    mode: "cash",
    jobId: "j-1",
    description: "CCTV kit purchase",
    createdAt: "2024-07-04",
  },
  {
    id: "tx-5",
    type: "expense",
    category: "Fuel / Travel",
    amount: 800,
    date: "2024-07-05",
    mode: "cash",
    description: "Diesel for site visits",
    createdAt: "2024-07-05",
  },
];

const ledger: LedgerEntry[] = [
  { id: "l-1", clientId: "c-2", date: "2024-07-04", type: "debit", amount: 18500, refId: "j-1", description: "Job #1 - CCTV camera installation", mode: "cash", createdAt: "2024-07-04" },
  { id: "l-2", clientId: "c-2", date: "2024-07-06", type: "credit", amount: 5000, refId: "j-1", description: "Payment received (advance) - Job #1", mode: "cash", createdAt: "2024-07-06" },
  { id: "l-3", clientId: "c-3", date: "2024-07-12", type: "debit", amount: 3600, refId: "j-2", description: "Job #2 - Printer cartridge refilling", mode: "upi", createdAt: "2024-07-12" },
  { id: "l-4", clientId: "c-3", date: "2024-07-12", type: "credit", amount: 3600, refId: "j-2", description: "Payment received - Job #2", mode: "upi", createdAt: "2024-07-12" },
  { id: "l-5", clientId: "c-1", date: "2024-07-19", type: "debit", amount: 2500, refId: "j-3", description: "Job #3 - Desktop repair", mode: "cash", createdAt: "2024-07-19" },
  { id: "l-6", clientId: "c-1", date: "2024-07-19", type: "credit", amount: 500, refId: "j-3", description: "Advance received - Job #3", mode: "cash", createdAt: "2024-07-19" },
];

export const seedDB: DB = {
  users,
  clients,
  jobs,
  amcs,
  attendance,
  salary,
  tada,
  transactions,
  ledger,
  settings: firm,
  jobCounter: jobs.length,
};
